"""create trips table

Revision ID: cea9b6e1852c
Revises: e748a401860e
Create Date: 2026-08-06 10:03:57.353097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea9b6e1852c'
down_revision: Union[str, None] = 'e748a401860e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('departure_city', sa.String(length=150), nullable=False),
    sa.Column('departure_lat', sa.Float(), nullable=True),
    sa.Column('departure_lon', sa.Float(), nullable=True),
    sa.Column('arrival_city', sa.String(length=150), nullable=False),
    sa.Column('arrival_lat', sa.Float(), nullable=True),
    sa.Column('arrival_lon', sa.Float(), nullable=True),
    sa.Column('departure_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELLED', 'COMPLETED', name='tripstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_departure_datetime'), 'trips', ['departure_datetime'], unique=False)
    op.create_index(op.f('ix_trips_driver_id'), 'trips', ['driver_id'], unique=False)
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_driver_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_departure_datetime'), table_name='trips')
    op.drop_table('trips')
    # ### end Alembic commands ###
